stages:
  - test
  - build
  - staging
  - deploy


image: node:latest

services:
  - mysql:latest
  - redis:latest
  - postgres:latest


cache:
  paths:
    - node_modules/

test_async:
  script:
    - npm init -y
    - npm install --save-dev typescript
    # - node ./specs/start.js ./specs/async.spec.js

test_db:
  script:
    - npm init -y
    - npm install --save-dev typescript
    # - node ./specs/start.js ./specs/db-postgres.spec.js

# deploys to production
deploy-job:
  image: ruby:latest # comment this line when shared runners are disabled
  stage: deploy 
  script:     
    - echo "Deploying application to Heroku..."
    - gem install dpl --verbose # comment this line when shared runners are disabled
    - dpl --provider=heroku --app=our-beautiful-app --api-key=$HEROKU_API_KEY 
    - echo "Application successfully deployed to Heroku" 


# build-job:
#   stage: build
#   script:
#     - echo "Running npm..."
#     - npm run
#     - echo "Finished running npm..."


# unit_test:
#     stage: test
#     script:
#         - echo "Running tests..."
#         - npm test

# staging_job:
#     stage: staging
#     script: 
#         - npm update

# deploy_job:
#     stage: deploy
#     script:
#         - echo "Deploying web app..."
