stages:
  - test
  - build
  - staging
  - deploy

image: node:latest

services:
  - redis:latest

cache:
  paths:
    - node_modules/

test_async:
  script:
    - npm init -y
    - npm install --save-dev typescript
    # - node ./specs/start.js ./specs/async.spec.js

test_db:
  script:
    - npm init -y
    - npm install --save-dev typescript
    # - node ./specs/start.js ./specs/db-postgres.spec.js

# deploys to production
deploy-job:
  image: ruby:latest # comment this line when shared runners are disabled
  stage: deploy 
  script:     
    - echo "Deploying application to Heroku..."
    - gem install dpl --verbose # comment this line when shared runners are disabled
    - dpl --provider=heroku --app=claraify --api-key=$HEROKU_API_KEY 
    - echo "Application successfully deployed to Heroku" 
