stages:
  - test
  - deploy

image: node:latest

test:
  stage: test 
  script:
    - echo "Running tests"

# deploys to production
deploy-production:
  image: ruby:latest # comment this line when shared runners are disabled
  stage: deploy
  only:
    - master
  script:
    - echo "Deploying application to production Heroku app..."
    - gem install dpl --verbose # comment this line when shared runners are disabled
    - dpl --provider=heroku --app=$PRODUCTION_APP_NAME --api-key=$HEROKU_API_KEY 
    - echo "Application successfully deployed to Heroku" 

# deploys to production
deploy-staging:
  image: ruby:latest # comment this line when shared runners are disabled
  stage: deploy
  only:
    - dev-branch
  script:
    - echo "Deploying application to staging Heroku app..."
    - gem install dpl --verbose # comment this line when shared runners are disabled
    - dpl --provider=heroku --app=$STAGING_APP_NAME --api-key=$HEROKU_API_KEY 
    - echo "Application successfully deployed to Heroku" 
